<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>چاپ دوزوله {{ $values['serial_number'] }}</title>
<style>
@page{size:{{ $layout->paper_width_mm }}mm {{ $layout->paper_height_mm }}mm;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0}.sheet{position:relative;width:{{ $layout->paper_width_mm }}mm;height:{{ $layout->paper_height_mm }}mm;overflow:hidden;direction:ltr;background-color:#fff;@if($layout->background_path)background-image:url('{{ asset('storage/'.$layout->background_path) }}');background-position:0 0;background-size:100% 100%;background-repeat:no-repeat;@endif}.field{position:absolute;overflow:hidden;display:flex;align-items:center;white-space:pre-wrap;line-height:1.15}.mask{position:absolute}.toolbar{position:fixed;z-index:99;top:12px;right:12px;display:flex;gap:8px;direction:rtl}.toolbar button,.toolbar a{border:0;border-radius:8px;padding:10px 14px;background:#047857;color:white;font:700 12px Tahoma;text-decoration:none;cursor:pointer}.toolbar a{background:#334155}.preview-note{position:fixed;z-index:98;bottom:12px;right:12px;background:#fff7ed;color:#9a3412;border:1px solid #fdba74;border-radius:8px;padding:8px 12px;font:700 11px Tahoma;direction:rtl}@media screen{body{min-height:100vh;display:flex;justify-content:center;align-items:flex-start;padding:64px 24px 32px;background:#e2e8f0}.sheet{flex:0 0 auto;box-shadow:0 18px 45px rgba(15,23,42,.28);border-radius:3px}}@media print{html,body{width:{{ $layout->paper_width_mm }}mm;height:{{ $layout->paper_height_mm }}mm;background:#fff}.toolbar,.preview-note{display:none}.sheet{box-shadow:none;border-radius:0}@if($mode==='original').sheet{background-image:none!important}.screen-only-mask{display:none!important}@endif}
</style></head><body>
<div class="toolbar"><button onclick="window.print()">چاپ {{ $copyTitle ?? ($mode==='original'?'اصل انجمن':'نسخه شرکت و راننده') }}</button>@if(empty($copyOnly))<a href="?mode={{ $mode==='original'?'copy':'original' }}">نمایش {{ $mode==='original'?'نسخه شرکت و راننده':'اصل انجمن' }}</a>@endif</div>
@if($mode==='original')<div class="preview-note">تصویر فقط برای پیش‌نمایش است و روی اصل انجمن چاپ نمی‌شود.</div>@endif
<main class="sheet">
@foreach($layout->masks as $mask)<div class="mask {{ $mode==='original'?'screen-only-mask':'' }}" style="left:{{ $mask->x_mm }}mm;top:{{ $mask->y_mm }}mm;width:{{ $mask->width_mm }}mm;height:{{ $mask->height_mm }}mm;background:{{ $mask->color }}"></div>@endforeach
@foreach($layout->fields as $field)
 @if(($mode==='original' && $field->show_on_original) || ($mode==='copy' && $field->show_on_copy))
 <div class="field" style="left:calc({{ $field->x_mm }}mm + {{ $layout->offset_x_mm }}mm);top:calc({{ $field->y_mm }}mm + {{ $layout->offset_y_mm }}mm);width:{{ $field->width_mm }}mm;height:{{ $field->height_mm }}mm;font:{{ $field->is_bold?'700':'400' }} {{ $field->font_size_pt }}pt '{{ $field->font_family }}',sans-serif;text-align:{{ $field->text_align }};justify-content:{{ $field->text_align==='center'?'center':($field->text_align==='right'?'flex-end':'flex-start') }};transform:rotate({{ $field->rotation_deg }}deg)">@if($field->field_key==='association_seal' && $layout->seal_path)<img src="{{ asset('storage/'.$layout->seal_path) }}" style="width:100%;height:100%;object-fit:contain">@elseif($field->field_key==='chairman_signature' && $layout->signature_path)<img src="{{ asset('storage/'.$layout->signature_path) }}" style="width:100%;height:100%;object-fit:contain">@else{{ $values[$field->field_key] ?? '' }}@endif</div>
 @endif
@endforeach
</main></body></html>
