@extends('layouts.app')
@section('header_title','گردش کار پرونده')
@section('content')
<div dir="rtl" class="mx-auto max-w-6xl space-y-6">
<section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-2xl font-black">گردش کار پرونده و پروانه</h1><p class="mt-2 text-sm text-slate-500">این صفحه فقط نمایشی است و هر تغییر توسط شرکت یا انجمن در تاریخچه ثبت می‌شود.</p></div><a href="{{ route('company.shahbaz.dossier.show') }}" class="rounded-xl border px-5 py-3 font-black">بازگشت به پرونده</a></div></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-black">مسیر پرونده</h2><div class="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4">@foreach($steps as $index=>$step)<article class="rounded-2xl border p-4 {{ $step['done'] ? 'border-emerald-200 bg-emerald-50' : ($step['current'] ? 'border-amber-300 bg-amber-50' : 'border-slate-200 bg-slate-50') }}"><div class="flex items-center justify-between"><span class="text-xs font-black text-slate-400">مرحله {{ $index+1 }}</span><span class="h-3 w-3 rounded-full {{ $step['done'] ? 'bg-emerald-500' : ($step['current'] ? 'bg-amber-500' : 'bg-slate-300') }}"></span></div><h3 class="mt-3 font-black">{{ $step['title'] }}</h3><p class="mt-2 text-xs {{ $step['done'] ? 'text-emerald-700' : ($step['current'] ? 'text-amber-700' : 'text-slate-400') }}">{{ $step['done'] ? 'انجام شده' : ($step['current'] ? 'در حال انجام' : 'در انتظار مراحل قبل') }}</p></article>@endforeach</div></section>
<section class="grid gap-4 md:grid-cols-3"><article class="rounded-2xl border bg-white p-5"><span class="text-xs text-slate-500">وضعیت شرکت</span><b class="mt-2 block">{{ $companyStatus }}</b></article><article class="rounded-2xl border bg-white p-5"><span class="text-xs text-slate-500">آخرین درخواست</span><b class="mt-2 block">{{ $licenseRequest?->tracking_code ?: 'ثبت نشده' }}</b><small>{{ $requestStatus ?: 'بدون وضعیت' }}</small></article><article class="rounded-2xl border bg-white p-5"><span class="text-xs text-slate-500">وضعیت هزینه</span><b class="mt-2 block">{{ $payment ? number_format($payment->amount).' ریال' : 'صورتحساب صادر نشده' }}</b><small>{{ $payment?->status }}</small></article></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-black">تاریخچه درخواست</h2><div class="mt-4 space-y-3">@forelse($licenseRequest?->histories ?? [] as $row)<div class="rounded-xl border p-4 text-sm"><b>{{ $row->from_status ?: 'شروع' }} ← {{ $row->to_status }}</b><p class="mt-2 text-slate-600">{{ $row->description }}</p><span class="mt-2 block text-xs text-slate-400">{{ verta($row->created_at)->format('Y/m/d H:i') }}</span></div>@empty<div class="rounded-xl border border-dashed p-5 text-sm text-slate-500">تاریخچه‌ای برای درخواست ثبت نشده است.</div>@endforelse</div></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-black">تاریخچه بررسی انجمن و شحباز</h2><div class="mt-4 space-y-3">@forelse($verificationHistories as $row)<div class="rounded-xl border p-4 text-sm"><b>{{ $row->from_status ?: 'شروع' }} ← {{ $row->to_status }}</b><p class="mt-2 text-slate-600">{{ $row->description }}</p><span class="mt-2 block text-xs text-slate-400">{{ verta($row->checked_at ?: $row->created_at)->format('Y/m/d H:i') }} — {{ $row->changedBy?->name ?? 'سامانه' }}</span></div>@empty<div class="rounded-xl border border-dashed p-5 text-sm text-slate-500">هنوز بررسی انجمن ثبت نشده است.</div>@endforelse</div></section>
</div>
@endsection
