<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $cmr->company_serial ?: $cmr->number }}</title>
<style>@page{size:A4 portrait;margin:8mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#102a72;margin:0;font-size:9px}.toolbar{display:flex;justify-content:flex-end;margin-bottom:8px}.toolbar button{background:#0b65c2;color:#fff;border:0;border-radius:7px;padding:9px 18px;font-weight:bold}.sheet{border:2px solid #16398c}.header{display:grid;grid-template-columns:1fr 1fr;min-height:120px}.cell{border:1px solid #16398c;padding:7px;min-height:68px}.no{font-size:16px;font-weight:bold;float:left;margin-right:6px}.title{text-align:center;font-size:22px;font-weight:bold;padding-top:12px}.serial{text-align:center;font-size:18px;margin-top:8px}.grid2{display:grid;grid-template-columns:1fr 1fr}.goods{width:100%;border-collapse:collapse}.goods th,.goods td{border:1px solid #16398c;padding:5px;text-align:left;vertical-align:top}.lower{display:grid;grid-template-columns:1.1fr .9fr}.signatures{display:grid;grid-template-columns:1fr 1fr 1fr}.signature{height:125px}.muted{font-size:8px;color:#334e91}.value{font-size:11px;color:#111;margin-top:8px;white-space:pre-wrap}.hash{font-size:7px;word-break:break-all;padding:5px}@media print{.toolbar{display:none}}</style></head><body>
<div class="toolbar"><button onclick="window.print()">Print / Save PDF</button></div><div class="sheet">
<div class="header"><div class="cell"><b>{{ $cmr->company?->name_en }}</b><div class="value">{{ $cmr->company?->address_en }}</div></div><div class="cell"><div class="title">INTERNATIONAL CONSIGNMENT NOTE — CMR</div><div class="serial">No. {{ $cmr->company_serial ?: $cmr->number }}</div><p class="muted">This carriage is subject, notwithstanding any clause to the contrary, to the Convention on the Contract for the International Carriage of Goods by Road (CMR).</p></div></div>
<div class="grid2"><div><div class="cell"><span class="no">1</span><b>Sender (name, address, country)</b><div class="value">{{ $cmr->consignor_name }}
{{ $cmr->consignor_address }} {{ $cmr->consignor_country_code }}</div></div><div class="cell"><span class="no">2</span><b>Consignee (name, address, country)</b><div class="value">{{ $cmr->consignee_name }}
{{ $cmr->consignee_address }} {{ $cmr->consignee_country_code }}</div></div><div class="cell"><span class="no">3</span><b>Place of delivery of the goods</b><div class="value">{{ $cmr->delivery_place }}</div></div><div class="cell"><span class="no">4</span><b>Place and date of taking over the goods</b><div class="value">{{ $cmr->taking_over_place }} — {{ optional($cmr->taking_over_at)->format('Y-m-d H:i') }}</div></div><div class="cell"><span class="no">5</span><b>Documents attached</b><div class="value">{{ implode(', ', $cmr->attached_documents ?: []) }}</div></div></div><div><div class="cell"><span class="no">16</span><b>Carrier (name, address, country)</b><div class="value">{{ $cmr->carrier_name }}
{{ $cmr->carrier_address }} {{ $cmr->carrier_country_code }}</div></div><div class="cell"><span class="no">17</span><b>Successive carriers</b><div class="value">{{ collect($cmr->successive_carriers ?: [])->pluck('name')->implode(', ') }}</div></div><div class="cell"><span class="no">18</span><b>Carrier's reservations and observations</b><div class="value">{{ $cmr->carrier_reservations }}</div></div></div></div>
<table class="goods"><thead><tr><th>6 Marks and numbers</th><th>7 Number of packages</th><th>8 Method of packing</th><th>9 Nature of the goods</th><th>10 Statistical No.</th><th>11 Gross weight kg</th><th>12 Volume m³</th></tr></thead><tbody>@foreach($cmr->goods as $good)<tr><td>{{ $good->marks_and_numbers }}</td><td>{{ $good->package_count }}</td><td>{{ $good->package_type }}</td><td>{{ $good->description }}@if($good->un_number)<br>UN {{ $good->un_number }} / ADR {{ $good->adr_class }}@endif</td><td>{{ $good->commodity_code }}</td><td>{{ $good->gross_weight_kg }}</td><td>{{ $good->volume_m3 }}</td></tr>@endforeach</tbody></table>
<div class="lower"><div><div class="cell"><span class="no">13</span><b>Sender's instructions</b><div class="value">{{ $cmr->sender_instructions }}</div></div><div class="cell"><span class="no">14</span><b>Instructions as to payment for carriage</b><div class="value">{{ $cmr->carriage_payment }}</div></div></div><div><div class="cell"><span class="no">19</span><b>Special agreements</b><div class="value">{{ $cmr->special_agreements }}</div></div><div class="cell"><span class="no">20</span><b>Charges</b><div class="value">{{ collect($cmr->charges ?: [])->map(fn($v,$k)=>$k.': '.$v)->implode("\n") }}</div></div></div></div>
@php($currentSignatures = $cmr->relationLoaded('signatures') ? $cmr->signatures->where('document_version', $cmr->version)->keyBy('signer_role') : collect())
<div class="cell"><span class="no">21</span><b>Established in / on</b><div class="value">{{ $cmr->established_at_place }} {{ optional($cmr->established_at_date)->format('Y-m-d') }}</div></div><div class="signatures"><div class="cell signature"><span class="no">22</span><b>Signature and stamp of the sender</b><div class="value">{{ $currentSignatures->get('sender')?->signer_name }}</div></div><div class="cell signature"><span class="no">23</span><b>Signature and stamp of the carrier / driver</b><div class="value">{{ $currentSignatures->get('carrier')?->signer_name ?: $currentSignatures->get('driver')?->signer_name }}</div></div><div class="cell signature"><span class="no">24</span><b>Goods received — Signature and stamp of consignee</b><div class="value">{{ $currentSignatures->get('consignee')?->signer_name }}</div></div></div><div class="hash">Electronic ID: {{ $cmr->uuid }} | Version: {{ $cmr->version }} | SHA-256: {{ $cmr->integrity_hash ?: 'Generated on issuance' }}@if($cmr->verification_code) | Verify: {{ route('cmr.verify', $cmr->verification_code) }}@endif</div></div></body></html>
