@extends(auth()->user()?->hasRole('company') ? 'layouts.app' : 'layouts.admin')
@section('header_title','شماره‌ها و قالب چاپ e-CMR')
@section('content')
<div class="space-y-5" dir="rtl">
@include('CMR.admin.partials.module-header',['title'=>'شماره‌های رسمی و قالب چاپ','subtitle'=>'مدیریت مخزن شماره و فرم چاپ اختصاصی هر شرکت'])
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<form method="GET" class="rounded-2xl border bg-white p-4"><label class="font-black">شرکت<select name="company_id" onchange="this.form.submit()" class="mt-2 w-full rounded-xl border p-3">@foreach($companies as $item)<option value="{{ $item->id }}" @selected($company?->id===$item->id)>{{ $item->name_fa ?: $item->name_en }}</option>@endforeach</select></label></form>
@if($company)
<section class="rounded-2xl border bg-white p-5">
 <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-black">مخزن شماره‌های رسمی CMR</h2><p class="text-sm text-slate-500">شماره آماده مصرف: <b>{{ number_format($availableSerialCount+$availablePoolCount) }}</b></p></div></div>
 <div class="mt-4 grid gap-4 lg:grid-cols-2">
  <details open class="rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"><summary class="cursor-pointer font-black text-emerald-900">روش اول: ثبت بازه پیوسته</summary>
   <form method="POST" action="{{ route('admin.cmr.company-settings.serial-pools.store',$company) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf
    <input name="name" required class="rounded-xl border p-3 md:col-span-2" placeholder="نام یا مرجع تحویل بازه">
    <input dir="ltr" name="prefix" class="rounded-xl border p-3" placeholder="پیشوند، مثال CMR-IR-">
    <input dir="ltr" name="suffix" class="rounded-xl border p-3" placeholder="پسوند اختیاری">
    <input dir="ltr" type="number" min="1" name="range_start" required class="rounded-xl border p-3" placeholder="از شماره">
    <input dir="ltr" type="number" min="1" name="range_end" required class="rounded-xl border p-3" placeholder="تا شماره">
    <input dir="ltr" type="number" min="1" max="20" name="number_padding" value="6" required class="rounded-xl border p-3" placeholder="تعداد رقم">
    <button class="rounded-xl bg-emerald-700 p-3 font-black text-white">ثبت بازه رسمی</button>
   </form>
  </details>
  <details class="rounded-xl border border-slate-200 bg-slate-50 p-4"><summary class="cursor-pointer font-black text-slate-800">روش دوم: ورود شماره‌های پراکنده</summary>
   <form method="POST" action="{{ route('admin.cmr.company-settings.serial-list.store',$company) }}" class="mt-4 space-y-3">@csrf<textarea dir="ltr" name="serials" required class="min-h-40 w-full rounded-xl border p-3" placeholder="CMR-IR-000001&#10;CMR-IR-000008"></textarea><p class="text-xs text-slate-500">برای شماره‌های غیرپیوسته؛ هر شماره در یک خط.</p><button class="rounded-xl bg-slate-800 px-5 py-3 font-black text-white">ثبت شماره‌های پراکنده</button></form>
  </details>
 </div>
 @if($serialPools->isNotEmpty())<div class="mt-4 overflow-hidden rounded-xl border"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-right">مرجع</th><th>از</th><th>تا</th><th>شماره بعدی</th></tr></thead><tbody>@foreach($serialPools as $pool)<tr class="border-t"><td class="p-3">{{ $pool->name }}</td><td dir="ltr">{{ $pool->prefix }}{{ str_pad($pool->range_start,$pool->number_padding,'0',STR_PAD_LEFT) }}{{ $pool->suffix }}</td><td dir="ltr">{{ $pool->prefix }}{{ str_pad($pool->range_end,$pool->number_padding,'0',STR_PAD_LEFT) }}{{ $pool->suffix }}</td><td dir="ltr">{{ $pool->next_number<=$pool->range_end ? $pool->prefix.str_pad($pool->next_number,$pool->number_padding,'0',STR_PAD_LEFT).$pool->suffix : 'تمام‌شده' }}</td></tr>@endforeach</tbody></table></div>@endif
</section>
<section class="rounded-2xl border bg-white p-5">
 <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-black">قالب‌های چاپ اختصاصی شرکت</h2><p class="text-sm text-slate-500">فرم خام را بارگذاری کنید و فیلدها را با ماوس روی آن قرار دهید.</p></div><a href="{{ route('admin.cmr.company-settings.print-templates.create',$company) }}" class="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white">ساخت قالب جدید</a></div>
 <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">@forelse($templates as $template)<div class="rounded-xl border p-4"><div class="flex items-center justify-between"><b>{{ $template->name }}</b>@if($template->is_default)<span class="rounded-full bg-emerald-100 px-2 py-1 text-xs text-emerald-700">پیش‌فرض</span>@endif</div><p class="mt-2 text-xs text-slate-500">{{ $template->print_mode==='preprinted'?'چاپ روی فرم خام':'چاپ کامل' }} · {{ count($template->field_layout??[]) }} فیلد</p><a href="{{ route('admin.cmr.company-settings.print-templates.edit',[$company,$template]) }}" class="mt-3 block rounded-lg border border-emerald-600 p-2 text-center text-sm font-bold text-emerald-700">ویرایش و جانمایی</a></div>@empty<div class="rounded-xl bg-slate-50 p-6 text-center text-slate-500 md:col-span-2 xl:col-span-3">هنوز قالب چاپی ثبت نشده است.</div>@endforelse</div>
</section>
<form method="POST" action="{{ route('admin.cmr.company-settings.update',$company) }}" class="space-y-5 rounded-2xl border bg-white p-5">@csrf @method('PUT')<div><h2 class="font-black">سیاست تخصیص راننده و ناوگان</h2><select name="assignment_policy" class="mt-3 w-full rounded-xl border p-3"><option value="same_company" @selected($settings->assignment_policy==='same_company')>فقط تحت پوشش همان شرکت</option><option value="any_registered" @selected($settings->assignment_policy==='any_registered')>هر راننده و ناوگان ثبت‌شده</option><option value="authorized_external" @selected($settings->assignment_policy==='authorized_external')>خارجی با تأیید مالک</option></select></div><div class="grid gap-4 lg:grid-cols-2"><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><label class="font-black"><input type="checkbox" name="origin_evidence_enabled" value="1" @checked($settings->origin_evidence_enabled)> شواهد تحویل بار در مبدأ فعال باشد</label><div class="mt-3 grid gap-2 text-sm"><label><input type="checkbox" name="origin_require_signature" value="1" @checked($settings->origin_require_signature)> امضای روی گوشی الزامی</label><label><input type="checkbox" name="origin_require_photo" value="1" @checked($settings->origin_require_photo)> عکس بار/پلمب الزامی</label><label><input type="checkbox" name="origin_require_gps" value="1" @checked($settings->origin_require_gps)> موقعیت GPS الزامی</label></div></div><div class="rounded-xl border border-indigo-200 bg-indigo-50 p-4"><label class="font-black"><input type="checkbox" name="destination_evidence_enabled" value="1" @checked($settings->destination_evidence_enabled)> شواهد تحویل در مقصد فعال باشد</label><div class="mt-3 grid gap-2 text-sm"><label><input type="checkbox" name="destination_require_signature" value="1" @checked($settings->destination_require_signature)> امضای گیرنده الزامی</label><label><input type="checkbox" name="destination_require_photo" value="1" @checked($settings->destination_require_photo)> عکس تحویل الزامی</label><label><input type="checkbox" name="destination_require_gps" value="1" @checked($settings->destination_require_gps)> موقعیت GPS الزامی</label></div></div></div><label class="block text-sm"><input type="checkbox" name="allow_delivery_exceptions" value="1" @checked($settings->allow_delivery_exceptions)> ثبت کسری، خسارت، تحویل ناقص و امتناع مجاز باشد</label><input type="hidden" name="print_language" value="en"><input type="hidden" name="require_latin_data" value="1"><button class="rounded-xl bg-slate-900 px-5 py-3 font-black text-white">ذخیره سیاست‌ها</button></form>
@endif
</div>
@endsection
