@extends('layouts.admin')
@section('header_title','تنظیمات شرکت، شماره و چاپ e-CMR')
@section('content')<div class="space-y-5" dir="rtl">
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<form method="GET" class="rounded-2xl border bg-white p-5"><label class="font-black">شرکت<select name="company_id" onchange="this.form.submit()" class="mt-2 w-full rounded-xl border p-3">@foreach($companies as $item)<option value="{{ $item->id }}" @selected($company?->id===$item->id)>{{ $item->name_fa ?: $item->name_en }}</option>@endforeach</select></label></form>
@if($company)<div class="grid gap-5 lg:grid-cols-2">
@include('CMR.admin.partials.serial-range-form')
<form method="POST" action="{{ route('admin.cmr.company-settings.update',$company) }}" class="space-y-4 rounded-2xl border bg-white p-5">@csrf @method('PUT')<h3 class="font-black">سیاست صدور شرکت</h3><label class="block">مالکیت راننده و ناوگان<select name="assignment_policy" class="mt-1 w-full rounded-xl border p-3"><option value="same_company" @selected($settings->assignment_policy==='same_company')>فقط تحت پوشش همان شرکت</option><option value="any_registered" @selected($settings->assignment_policy==='any_registered')>هر راننده و ناوگان ثبت‌شده</option><option value="authorized_external" @selected($settings->assignment_policy==='authorized_external')>خارجی با تأیید مالک</option></select></label><input type="hidden" name="print_language" value="en"><input type="hidden" name="require_latin_data" value="1"><p class="rounded-xl bg-indigo-50 p-3 text-sm text-indigo-800">شماره رسمی CMR فقط از شماره‌ها یا بازه‌ای که شرکت تحویل داده تخصیص می‌یابد؛ ورود شماره هنگام صدور حذف شده است.</p><button class="rounded-xl bg-sky-600 px-5 py-3 font-black text-white">ذخیره سیاست</button></form>
<form method="POST" action="{{ route('admin.cmr.company-settings.serial-list.store',$company) }}" class="space-y-3 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">شماره‌های رسمی تحویلی شرکت</h3><p class="text-sm text-slate-600">هر شماره را در یک خط وارد کنید. هر شماره فقط یک‌بار مصرف می‌شود.</p><textarea dir="ltr" name="serials" required class="min-h-40 w-full rounded-xl border p-3" placeholder="CMR-IR-000001&#10;CMR-IR-000002"></textarea><button class="rounded-xl bg-violet-600 px-5 py-3 font-black text-white">ثبت شماره‌ها</button><p class="text-sm">شماره آماده مصرف: {{ $availableSerialCount }}</p></form>
<form method="POST" action="{{ route('admin.cmr.company-settings.serial-pools.store',$company) }}" class="space-y-4 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">ثبت بازه رسمی شرکت</h3><input name="name" required class="w-full rounded-xl border p-3" placeholder="نام یا مرجع بازه"><input dir="ltr" name="prefix" class="w-full rounded-xl border p-3" placeholder="Prefix, e.g. IR-"><div class="grid grid-cols-2 gap-3"><input type="number" min="1" name="range_start" required class="rounded-xl border p-3" placeholder="شروع"><input type="number" min="1" name="range_end" required class="rounded-xl border p-3" placeholder="پایان"></div><button class="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white">ثبت بازه</button>@foreach($serialPools as $pool)<div class="border-t py-2 text-sm" dir="ltr">{{ $pool->name }}: {{ $pool->prefix }}{{ $pool->range_start }} — {{ $pool->prefix }}{{ $pool->range_end }} | Next: {{ $pool->next_number }}</div>@endforeach</form>
<form method="POST" action="{{ route('admin.cmr.company-settings.print-templates.store',$company) }}" class="space-y-4 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">قالب چاپ شرکت</h3><input name="name" required class="w-full rounded-xl border p-3" placeholder="نام قالب"><select name="print_mode" class="w-full rounded-xl border p-3"><option value="full">چاپ کامل با کادر</option><option value="preprinted">چاپ مقادیر روی برگه آماده</option></select><select name="header_mode" class="w-full rounded-xl border p-3"><option value="company_profile">اطلاعات پروفایل شرکت</option><option value="custom">سربرگ اختصاصی</option><option value="none">بدون سربرگ</option></select><input dir="ltr" name="custom_company_name" class="w-full rounded-xl border p-3" placeholder="Custom Latin company name"><input dir="ltr" name="custom_company_contact" class="w-full rounded-xl border p-3" placeholder="Phone / Email / Website"><textarea dir="ltr" name="custom_company_address" class="w-full rounded-xl border p-3" placeholder="Latin address"></textarea><label><input type="checkbox" name="is_default" value="1"> قالب پیش‌فرض</label><button class="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">ثبت قالب</button></form>
</div>@endif</div>@endsection
