@extends('layouts.admin')
@section('header_title', 'تنظیمات شرکتی e-CMR')
@section('content')
<div class="space-y-5" dir="rtl">
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-emerald-700">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<form method="GET" class="rounded-2xl border bg-white p-5"><label class="font-black">شرکت<select name="company_id" onchange="this.form.submit()" class="mt-2 w-full rounded-xl border p-3">@foreach($companies as $item)<option value="{{ $item->id }}" @selected($company?->id === $item->id)>{{ $item->name_fa ?: $item->name_en }}</option>@endforeach</select></label></form>
@if($company)
<div class="grid gap-5 lg:grid-cols-2">
<form method="POST" action="{{ route('admin.cmr.company-settings.update',$company) }}" class="space-y-4 rounded-2xl border bg-white p-5">@csrf @method('PUT')<h3 class="font-black">سیاست صدور شرکت</h3><label class="block">مالکیت راننده و ناوگان<select name="assignment_policy" class="mt-1 w-full rounded-xl border p-3"><option value="same_company" @selected($settings->assignment_policy==='same_company')>فقط تحت پوشش همان شرکت</option><option value="any_registered" @selected($settings->assignment_policy==='any_registered')>هر راننده و ناوگان ثبت‌شده</option><option value="authorized_external" @selected($settings->assignment_policy==='authorized_external')>خارجی با تأیید مالک</option></select></label><label class="block">روش شماره سریال<select name="serial_mode" class="mt-1 w-full rounded-xl border p-3"><option value="system" @selected($settings->serial_mode==='system')>شماره خودکار سامانه</option><option value="manual" @selected($settings->serial_mode==='manual')>ورود دستی شماره شرکت</option><option value="pool" @selected($settings->serial_mode==='pool')>تخصیص از بازه شرکت</option></select></label><input type="hidden" name="print_language" value="en"><input type="hidden" name="require_latin_data" value="1"><p class="text-sm text-amber-700">نسخه رسمی و چاپی CMR فقط با داده لاتین صادر می‌شود.</p><button class="rounded-xl bg-sky-600 px-5 py-3 font-black text-white">ذخیره سیاست</button></form>
<form method="POST" action="{{ route('admin.cmr.company-settings.serial-pools.store',$company) }}" class="space-y-4 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">ثبت بازه شماره CMR</h3><input name="name" required class="w-full rounded-xl border p-3" placeholder="نام بازه"><input name="prefix" class="w-full rounded-xl border p-3" placeholder="پیشوند اختیاری، مانند IR-"><div class="grid grid-cols-2 gap-3"><input type="number" min="1" name="range_start" required class="rounded-xl border p-3" placeholder="شروع"><input type="number" min="1" name="range_end" required class="rounded-xl border p-3" placeholder="پایان"></div><button class="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white">ثبت بازه</button><div class="text-sm">@foreach($serialPools as $pool)<div class="border-t py-2">{{ $pool->name }}: {{ $pool->prefix }}{{ $pool->range_start }} تا {{ $pool->prefix }}{{ $pool->range_end }} — شماره بعدی {{ $pool->next_number }}</div>@endforeach</div></form>
</div>
<form method="POST" action="{{ route('admin.cmr.company-settings.print-templates.store',$company) }}" class="space-y-4 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">قالب چاپ شرکت</h3><div class="grid gap-3 md:grid-cols-3"><input name="name" required class="rounded-xl border p-3" placeholder="نام قالب"><select name="print_mode" class="rounded-xl border p-3"><option value="full">چاپ کامل با کادر و سربرگ</option><option value="preprinted">چاپ روی برگه آماده، فقط مقادیر</option></select><select name="header_mode" class="rounded-xl border p-3"><option value="company_profile">لوگو و اطلاعات پروفایل شرکت</option><option value="custom">سربرگ اختصاصی قالب</option><option value="none">بدون سربرگ</option></select><input name="custom_company_name" class="rounded-xl border p-3" placeholder="نام لاتین اختصاصی"><input name="custom_company_contact" class="rounded-xl border p-3" placeholder="تلفن/ایمیل/وب‌سایت"><textarea name="custom_company_address" class="rounded-xl border p-3" placeholder="نشانی لاتین"></textarea></div><label class="flex gap-2"><input type="checkbox" name="is_default" value="1"> قالب پیش‌فرض شرکت</label><button class="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">ثبت قالب</button><div class="grid gap-3 md:grid-cols-3">@foreach($templates as $template)<div class="rounded-xl border p-3"><b>{{ $template->name }}</b><p class="text-sm text-slate-500">{{ $template->print_mode }} / {{ $template->header_mode }} @if($template->is_default)— پیش‌فرض @endif</p></div>@endforeach</div></form>
@endif
</div>
@endsection
