@extends('layouts.admin')
@section('header_title', 'ایجاد پیش‌نویس e-CMR')
@section('content')
<form method="POST" action="{{ route('admin.cmr.store') }}" class="space-y-5" dir="rtl">@csrf
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<div class="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-3"><label>شرکت<select name="company_id" class="mt-1 w-full rounded-xl border p-2" required>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name_fa ?: $company->name }}</option>@endforeach</select></label><label>راننده<select name="driver_id" class="mt-1 w-full rounded-xl border p-2"><option value="">—</option>@foreach($drivers as $driver)<option value="{{ $driver->id }}">{{ $driver->first_name_en }} {{ $driver->last_name_en }}</option>@endforeach</select></label><label>ناوگان<select name="fleet_id" class="mt-1 w-full rounded-xl border p-2"><option value="">—</option>@foreach($fleets as $fleet)<option value="{{ $fleet->id }}">{{ $fleet->transit_plate ?: $fleet->smart_card_number ?: '#'.$fleet->id }}</option>@endforeach</select></label><label>زبان رسمی<input name="language" value="en" readonly class="mt-1 w-full rounded-xl border bg-slate-100 p-2"></label><label>شماره سریال شرکت (در حالت دستی)<input name="company_serial" class="mt-1 w-full rounded-xl border p-2" dir="ltr"></label><p class="self-end text-xs text-amber-700">تمام اطلاعات چاپی CMR باید با حروف لاتین وارد شوند.</p></div>
@foreach(['consignor'=>'فرستنده','carrier'=>'حمل‌کننده','consignee'=>'گیرنده'] as $key=>$title)<div class="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-3"><h3 class="md:col-span-3 font-black">{{ $title }}</h3><input class="rounded-xl border p-2" name="{{ $key }}_name" placeholder="نام رسمی" required><input class="rounded-xl border p-2" name="{{ $key }}_identifier" placeholder="شناسه"><input class="rounded-xl border p-2" name="{{ $key }}_country_code" maxlength="2" placeholder="کد کشور مانند IR"><textarea class="rounded-xl border p-2 md:col-span-3" name="{{ $key }}_address" placeholder="نشانی"></textarea></div>@endforeach
<div class="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-2"><input class="rounded-xl border p-2" name="taking_over_place" placeholder="محل تحویل کالا به حمل‌کننده" required><input class="rounded-xl border p-2" type="datetime-local" name="taking_over_at"><input class="rounded-xl border p-2" name="delivery_place" placeholder="محل تحویل نهایی" required><input class="rounded-xl border p-2" type="datetime-local" name="planned_delivery_at"></div>
<div class="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-5"><h3 class="md:col-span-5 font-black">ردیف کالا</h3><input class="rounded-xl border p-2 md:col-span-2" name="goods[0][description]" placeholder="شرح کالا" required><input class="rounded-xl border p-2" name="goods[0][package_type]" placeholder="نوع بسته"><input class="rounded-xl border p-2" type="number" step="0.001" name="goods[0][package_count]" placeholder="تعداد"><input class="rounded-xl border p-2" type="number" step="0.001" name="goods[0][gross_weight_kg]" placeholder="وزن kg"></div>
<button class="rounded-xl bg-sky-600 px-6 py-3 font-black text-white">ذخیره پیش‌نویس</button></form>
@endsection
