@extends('layouts.admin')
@section('header_title','اطلاعات پایه e-CMR')
@section('content')<div class="space-y-5" dir="rtl">
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<form method="GET" class="rounded-2xl border bg-white p-5"><label class="font-black">شرکت<select name="company_id" onchange="this.form.submit()" class="mt-2 w-full rounded-xl border p-3">@foreach($companies as $item)<option value="{{ $item->id }}" @selected($company?->id===$item->id)>{{ $item->name_fa ?: $item->name_en }}</option>@endforeach</select></label></form>
@if($company)<div class="grid gap-5 lg:grid-cols-3">
<form method="POST" action="{{ route('admin.cmr.master-data.parties.store',$company) }}" class="space-y-3 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">طرف تجاری</h3><select name="party_type" class="w-full rounded-xl border p-2"><option value="consignor">فرستنده</option><option value="consignee">گیرنده</option><option value="carrier">حمل‌کننده</option><option value="successive_carrier">حمل‌کننده بعدی</option></select><input dir="ltr" name="legal_name" required class="w-full rounded-xl border p-2" placeholder="Legal name"><input dir="ltr" name="identifier" class="w-full rounded-xl border p-2" placeholder="Identifier"><input dir="ltr" name="country_code" maxlength="2" class="w-full rounded-xl border p-2" placeholder="Country code"><textarea dir="ltr" name="address" class="w-full rounded-xl border p-2" placeholder="Address"></textarea><button class="rounded-xl bg-sky-600 px-4 py-2 font-bold text-white">ذخیره طرف تجاری</button></form>
<form method="POST" action="{{ route('admin.cmr.master-data.locations.store',$company) }}" class="space-y-3 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">مکان پرتکرار</h3><select name="location_type" class="w-full rounded-xl border p-2"><option value="taking_over">محل تحویل به حمل‌کننده</option><option value="delivery">محل تحویل نهایی</option></select><input dir="ltr" name="name" required class="w-full rounded-xl border p-2" placeholder="Place, city, country"><input dir="ltr" name="country_code" maxlength="2" class="w-full rounded-xl border p-2" placeholder="Country code"><button class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">ذخیره مکان</button></form>
<form method="POST" action="{{ route('admin.cmr.master-data.goods.store',$company) }}" class="space-y-3 rounded-2xl border bg-white p-5">@csrf<h3 class="font-black">الگوی کالا</h3>@foreach(['name'=>'Template name','description'=>'Nature of goods','package_type'=>'Packing method','commodity_code'=>'Commodity code','un_number'=>'UN number','adr_class'=>'ADR class'] as $key=>$placeholder)<input dir="ltr" name="{{ $key }}" @required(in_array($key,['name','description'])) class="w-full rounded-xl border p-2" placeholder="{{ $placeholder }}">@endforeach<button class="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">ذخیره الگوی کالا</button></form>
</div><div class="grid gap-5 lg:grid-cols-3"><div class="rounded-2xl border bg-white p-5"><h3 class="font-black">طرف‌های ذخیره‌شده</h3>@foreach($parties as $item)<div class="border-t py-2 text-sm">{{ $item->party_type }} — {{ $item->legal_name }}</div>@endforeach</div><div class="rounded-2xl border bg-white p-5"><h3 class="font-black">مکان‌های ذخیره‌شده</h3>@foreach($locations as $item)<div class="border-t py-2 text-sm">{{ $item->location_type }} — {{ $item->name }}</div>@endforeach</div><div class="rounded-2xl border bg-white p-5"><h3 class="font-black">کالاهای ذخیره‌شده</h3>@foreach($goodsTemplates as $item)<div class="border-t py-2 text-sm">{{ $item->name }} — {{ $item->description }}</div>@endforeach</div></div>@endif
</div>@endsection
