@extends('layouts.admin')
@section('header_title','تعرفه e-CMR')
@section('content')
@include('CMR.admin.partials.module-header',['title'=>'تعرفه و امور مالی e-CMR','subtitle'=>'کسر هزینه صدور از کیف پول شرکت و نگهداری تاریخچه تعرفه'])
<div class="space-y-5" dir="rtl">
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-emerald-700">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.cmr.settings.update') }}" class="max-w-2xl space-y-5 rounded-2xl border bg-white p-6">@csrf @method('PUT')
 <div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><label class="flex items-center gap-2 font-black text-emerald-900"><input type="checkbox" name="billing_enabled" value="1" @checked($settings->billing_enabled)> کسر هزینه هنگام صدور فعال باشد</label><p class="mt-2 text-sm text-emerald-800">با صدور رسمی هر CMR، مبلغ زیر مستقیماً از کیف پول شرکت صادرکننده کسر می‌شود.</p></div>
 <label class="block font-bold">مبلغ صدور به ریال<input id="cmr-fee" class="mt-1 w-full rounded-xl border p-3 text-left text-lg font-black" dir="ltr" type="number" min="0" step="1" name="issuance_fee" value="{{ (int)$settings->issuance_fee }}" required><span id="cmr-fee-preview" class="mt-2 block text-sm text-slate-500"></span></label>
 <div class="rounded-xl bg-slate-100 p-3 text-sm"><b>واحد مالی:</b> ریال ایران <span dir="ltr">(IRR)</span><input type="hidden" name="currency" value="IRR"></div>
 <p class="text-sm text-amber-700">تعرفه جدید فقط روی صدورهای بعدی اثر دارد و مبلغ هر سند هنگام صدور در همان سند قفل می‌شود. لغو سند بدون استرداد وجه است.</p>
 <button class="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white">ذخیره تعرفه جاری</button>
</form>
<section class="rounded-2xl border bg-white p-5"><div><h3 class="font-black">تاریخچه تعرفه</h3><p class="mt-1 text-xs text-slate-500">ویرایش تاریخچه فقط برای اصلاح اشتباه ثبتی است و تعرفه جاری را تغییر نمی‌دهد؛ دلیل اصلاح ذخیره می‌شود.</p></div>
 <div class="mt-4 space-y-3">@forelse($history as $item)<details class="rounded-xl border p-4"><summary class="cursor-pointer list-none"><div class="grid items-center gap-2 text-sm md:grid-cols-5"><b>{{ number_format((float)$item->issuance_fee) }} ریال</b><span>{{ $item->billing_enabled?'فعال':'غیرفعال' }}</span><span>کاربر #{{ $item->changed_by?:'—' }}</span><span dir="ltr">{{ verta($item->effective_from)->format('Y/m/d H:i') }}</span><span class="font-bold text-emerald-700">ویرایش</span></div></summary>
  <form method="POST" action="{{ route('admin.cmr.settings.history.update',$item) }}" class="mt-4 grid gap-3 border-t pt-4 md:grid-cols-2">@csrf @method('PUT')<label class="text-sm">مبلغ به ریال<input dir="ltr" type="number" min="0" step="1" name="issuance_fee" value="{{ (int)$item->issuance_fee }}" required class="mt-1 w-full rounded-lg border p-2"></label><label class="text-sm">زمان اثرگذاری (هجری شمسی)<input dir="ltr" name="effective_from_jalali" value="{{ verta($item->effective_from)->format('Y/m/d H:i') }}" required class="mt-1 w-full rounded-lg border p-2" placeholder="1405/04/27 12:30"></label><label class="text-sm md:col-span-2"><input type="checkbox" name="billing_enabled" value="1" @checked($item->billing_enabled)> فعال بوده است</label><label class="text-sm md:col-span-2">دلیل اصلاح<textarea name="correction_reason" required class="mt-1 w-full rounded-lg border p-2" placeholder="علت ویرایش این ردیف تاریخچه">{{ $item->correction_reason }}</textarea></label><button class="rounded-lg bg-slate-800 p-2 font-bold text-white md:col-span-2">ثبت اصلاح تاریخچه</button>@if($item->corrected_at)<p class="text-xs text-amber-700 md:col-span-2">آخرین اصلاح: {{ verta($item->corrected_at)->format('Y/m/d H:i') }} توسط کاربر #{{ $item->corrected_by }}</p>@endif</form>
 </details>@empty<p class="rounded-xl bg-slate-50 p-6 text-center text-slate-400">هنوز تغییری ثبت نشده است.</p>@endforelse</div>
</section></div>
<script>const fee=document.getElementById('cmr-fee'),preview=document.getElementById('cmr-fee-preview');function renderFee(){preview.textContent=(Number(fee.value||0)).toLocaleString('fa-IR')+' ریال'}fee.addEventListener('input',renderFee);renderFee();</script>
@endsection
