@extends('layouts.admin')
@section('header_title', 'جزئیات e-CMR')
@section('content')
<div class="space-y-5" dir="rtl">
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-emerald-700">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-700">{{ $errors->first() }}</div>@endif
<div class="flex justify-end"><a href="{{ route('admin.cmr.print', $cmr) }}" target="_blank" class="rounded-xl border border-sky-600 px-5 py-2 font-black text-sky-700">پیش‌نمایش برگه استاندارد ۲۴ خانه‌ای</a></div>
<div class="flex items-center justify-between rounded-2xl border bg-white p-5"><div><h2 class="text-xl font-black">{{ $cmr->number ?: 'پیش‌نویس #'.$cmr->id }}</h2><p class="text-sm text-slate-500">{{ $cmr->company->name_fa ?: $cmr->company->name }} — {{ $cmr->status }}</p></div>@if($cmr->status === 'draft')<form method="POST" action="{{ route('admin.cmr.issue',$cmr) }}">@csrf<button class="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white" onclick="return confirm('CMR صادر و هزینه از کیف پول شرکت کسر شود؟')">صدور رسمی</button></form>@endif</div>
<div class="grid gap-4 md:grid-cols-3">@foreach([['فرستنده',$cmr->consignor_name,$cmr->consignor_address],['حمل‌کننده',$cmr->carrier_name,$cmr->carrier_address],['گیرنده',$cmr->consignee_name,$cmr->consignee_address]] as $party)<div class="rounded-2xl border bg-white p-5"><h3 class="font-black">{{ $party[0] }}</h3><p>{{ $party[1] }}</p><p class="text-sm text-slate-500">{{ $party[2] }}</p></div>@endforeach</div>
<div class="rounded-2xl border bg-white p-5"><h3 class="mb-3 font-black">کالاها</h3>@foreach($cmr->goods as $good)<div class="border-t py-2">{{ $good->line_number }}. {{ $good->description }} — {{ $good->package_count }} {{ $good->package_type }} — {{ $good->gross_weight_kg }} kg</div>@endforeach</div>
<div class="rounded-2xl border bg-white p-5"><h3 class="mb-3 font-black">سوابق</h3>@foreach($cmr->events as $event)<div class="border-t py-2 text-sm"><b>{{ $event->event_type }}</b> — {{ $event->description }} — {{ $event->occurred_at }}</div>@endforeach</div>
@if(in_array($cmr->status, ['draft','issued'], true))<form method="POST" action="{{ route('admin.cmr.cancel',$cmr) }}" class="rounded-2xl border border-rose-200 bg-rose-50 p-5">@csrf<label class="block font-black text-rose-800">لغو سند بدون استرداد وجه<textarea name="reason" required maxlength="2000" class="mt-2 w-full rounded-xl border border-rose-200 bg-white p-3" placeholder="دلیل لغو"></textarea></label><button class="mt-3 rounded-xl bg-rose-600 px-5 py-2 font-black text-white" onclick="return confirm('سند لغو شود؟ مبلغ صدور مسترد نخواهد شد.')">لغو قطعی</button></form>@endif
<div class="grid gap-5 lg:grid-cols-2">
 <div class="rounded-2xl border bg-white p-5"><h3 class="mb-3 font-black">مدارک پیوست</h3>
  @foreach($cmr->attachments as $attachment)<div class="flex items-center justify-between border-t py-2 text-sm"><span>{{ $attachment->document_type }} — {{ $attachment->original_name }}</span><a class="text-sky-700" href="{{ route('admin.cmr.attachments.download',[$cmr,$attachment]) }}">دریافت</a></div>@endforeach
  <form method="POST" enctype="multipart/form-data" action="{{ route('admin.cmr.attachments.store',$cmr) }}" class="mt-3 grid gap-2">@csrf<input name="document_type" required class="rounded-xl border p-2" placeholder="نوع مدرک؛ مانند Commercial invoice"><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png" required class="rounded-xl border p-2"><button class="rounded-xl bg-sky-600 px-4 py-2 font-bold text-white">بارگذاری و ثبت هش فایل</button></form>
 </div>
 <div class="rounded-2xl border bg-white p-5"><h3 class="mb-3 font-black">تأییدهای نسخه {{ $cmr->version }}</h3>
  @foreach($cmr->signatures as $signature)<div class="border-t py-2 text-sm">{{ $signature->signer_role }} — {{ $signature->signer_name }} — {{ $signature->signed_at }}</div>@endforeach
  @if($cmr->status !== 'draft')<form method="POST" action="{{ route('admin.cmr.signatures.store',$cmr) }}" class="mt-3 grid gap-2">@csrf<select name="signer_role" class="rounded-xl border p-2"><option value="sender">Sender / فرستنده</option><option value="carrier">Carrier / حمل‌کننده</option></select><input dir="ltr" name="signer_name" required class="rounded-xl border p-2" placeholder="Latin signer name"><input dir="ltr" name="signer_identifier" class="rounded-xl border p-2" placeholder="Identifier"><textarea dir="ltr" name="reservation" class="rounded-xl border p-2" placeholder="Reservation, if any"></textarea><label class="text-sm"><input type="checkbox" name="confirmed" value="1" required> شخص تأییدکننده، نسخه و هش فعلی سند را مشاهده و تأیید کرده است.</label><button class="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">ثبت تأیید الکترونیکی</button></form>@endif
 </div>
</div>
@if(in_array($cmr->status,['issued','accepted','in_transit'],true))<form method="POST" action="{{ route('admin.cmr.amendments.store',$cmr) }}" class="grid gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 md:grid-cols-2">@csrf<h3 class="font-black md:col-span-2">اصلاحیه نسخه‌دار — بدون حذف سابقه قبلی</h3><input dir="ltr" name="delivery_place" class="rounded-xl border p-2" placeholder="New delivery place"><input type="datetime-local" name="planned_delivery_at" class="rounded-xl border p-2"><textarea dir="ltr" name="sender_instructions" class="rounded-xl border p-2" placeholder="Sender instructions"></textarea><textarea dir="ltr" name="carrier_reservations" class="rounded-xl border p-2" placeholder="Carrier reservations"></textarea><textarea dir="ltr" name="special_agreements" class="rounded-xl border p-2 md:col-span-2" placeholder="Special agreements"></textarea><textarea name="reason" required class="rounded-xl border p-2 md:col-span-2" placeholder="دلیل حقوقی اصلاح"></textarea><button class="rounded-xl bg-amber-600 px-4 py-2 font-bold text-white md:col-span-2" onclick="return confirm('نسخه جدید ایجاد شود؟ نسخه قبلی حذف نخواهد شد.')">ثبت اصلاحیه و ایجاد نسخه جدید</button></form>@endif
@if($cmr->verification_code)<a target="_blank" href="{{ route('cmr.verify',$cmr->verification_code) }}" class="block rounded-2xl bg-emerald-50 p-4 text-center font-black text-emerald-700">مشاهده صفحه عمومی اعتبارسنجی سند</a>@endif
@if($cmr->integrity_hash)<div class="break-all rounded-2xl bg-slate-900 p-4 font-mono text-xs text-white">SHA-256: {{ $cmr->integrity_hash }}</div>@endif
</div>
@endsection
