@extends('layouts.admin')
@section('header_title','کنترل دستی شحباز')
@section('content')
<link rel="stylesheet" href="{{ asset('assets/css/persian-datepicker.vendor.min.css') }}"><style>.datepicker-plot-area{font-family:'Vazirmatn',Tahoma,sans-serif!important;z-index:99999!important}.jalali-picker{cursor:pointer}</style>
<div dir="rtl" class="mx-auto max-w-5xl rounded-2xl border bg-white p-6"><h1 class="text-xl font-black">{{ $company->name_fa }}</h1>
@if(session('success'))<div class="my-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="my-4 rounded-xl bg-rose-50 p-4 text-rose-800">{{ $errors->first() }}</div>@endif
<div class="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm"><span>شناسه ملی: <b>{{ $company->national_id }}</b></span><span>شماره ثبت: <b>{{ $company->registration_number }}</b></span><span>مدیرعامل: <b>{{ $company->ceo_name }}</b></span><span>کد ملی مدیرعامل: <b>{{ $company->ceo_national_code }}</b></span><span class="col-span-2">آدرس: <b>{{ $company->address_fa }}</b></span><span>نوع فعالیت: <b>{{ $company->activity_type }}</b></span><span>وضعیت: <b>{{ $company->shahbaz_verification_status }}</b></span></div>
<section class="mt-6 rounded-2xl border bg-white p-5"><h2 class="text-lg font-black">پرونده کامل شرکت برای کنترل انجمن</h2><p class="mt-1 text-sm text-slate-500">هر بخش را باز کنید و قبل از ثبت نتیجه بررسی نمایید.</p><div class="mt-4 space-y-3">
<details open class="rounded-xl border p-4"><summary class="cursor-pointer font-black">درخواست‌های پروانه ({{ $licenseRequests->count() }})</summary><div class="mt-3 grid gap-3 md:grid-cols-2">@forelse($licenseRequests as $item)<div class="rounded-lg bg-slate-50 p-3 text-sm"><b>{{ $item->tracking_code }}</b><div class="mt-2">نوع: {{ $item->request_type }} — حوزه: {{ $item->activity_scope ?: 'ثبت نشده' }}</div><div>نوع فعالیت: {{ $item->activity_type ?: 'ثبت نشده' }} — وضعیت: {{ $item->status }}</div><p class="mt-2 text-slate-600">{{ $item->company_description }}</p></div>@empty<div class="text-slate-500">درخواستی ثبت نشده است.</div>@endforelse</div></details>
@foreach(['personnel'=>'پرسنل','board'=>'هیئت‌مدیره','shareholders'=>'سهامداران'] as $type=>$label)<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">{{ $label }} ({{ $dossier['people']->get($type,collect())->count() }})</summary><div class="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">@forelse($dossier['people']->get($type,collect()) as $relation)<div class="rounded-lg bg-slate-50 p-3 text-sm"><b>{{ $relation->person?->first_name }} {{ $relation->person?->last_name }}</b><div class="mt-2">کد ملی/گذرنامه: {{ $relation->person?->national_code ?: $relation->person?->passport_number }}</div><div>عنوان: {{ $relation->job_title ?: $relation->board_position ?: $relation->shareholder_type ?: 'ثبت نشده' }}</div>@if($type==='shareholders')<div>سهم: {{ $relation->share_percentage ?? 0 }}٪ — {{ number_format((float)($relation->share_amount ?? 0)) }} ریال</div>@endif</div>@empty<div class="text-slate-500">رکوردی ثبت نشده است.</div>@endforelse</div></details>@endforeach
<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">ناوگان مشترک ({{ $dossier['fleets']->count() }})</summary><div class="mt-3 grid gap-3 md:grid-cols-3">@forelse($dossier['fleets'] as $fleet)<div class="rounded-lg bg-slate-50 p-3 text-sm"><b>{{ $fleet->transit_plate ?: 'پلاک ثبت نشده' }}</b><div class="mt-2">کارت هوشمند: {{ $fleet->smart_card_number ?: '—' }}</div><div>نوع وسیله: {{ $fleet->truck_type ?: '—' }}</div></div>@empty<div class="text-slate-500">ناوگانی متصل نیست.</div>@endforelse</div></details>
<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">محل و امکانات</summary>@if($dossier['facility'])<div class="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><div>{{ $dossier['facility']->location_type }} — {{ $dossier['facility']->ownership_type }}</div><div class="mt-2">کدپستی: {{ $dossier['facility']->postal_code }} — تلفن: {{ $dossier['facility']->phone }}</div><div class="mt-2">نشانی: {{ $dossier['facility']->address }}</div><div class="mt-3 grid gap-2 md:grid-cols-3">@foreach($dossier['facility']->facilities ?? [] as $facility)<span class="rounded bg-white p-2">{{ $facility['type'] ?? 'امکان' }}: {{ $facility['area'] ?? '—' }} متر</span>@endforeach</div></div>@else<div class="mt-3 text-slate-500">اطلاعاتی ثبت نشده است.</div>@endif</details>
<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">روزنامه رسمی ({{ $dossier['gazettes']->count() }})</summary><div class="mt-3 space-y-2">@forelse($dossier['gazettes'] as $gazette)<div class="rounded-lg bg-slate-50 p-3 text-sm"><b>{{ $gazette->gazette_number }} — {{ $gazette->change_group }}</b><div class="mt-1">{{ verta($gazette->gazette_date)->format('Y/m/d') }} — {{ $gazette->subject }}</div></div>@empty<div class="text-slate-500">رکوردی ثبت نشده است.</div>@endforelse</div></details>
<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">ثبت شرکت</summary>@if($dossier['registration'])<div class="mt-3 rounded-lg bg-slate-50 p-3 text-sm">تاریخ ثبت: {{ verta($dossier['registration']->registered_on)->format('Y/m/d') }} — شهر: {{ $dossier['registration']->registration_city }} — نوع حقوقی: {{ $dossier['registration']->legal_type }}<div class="mt-2">معرفی‌نامه: {{ $dossier['registration']->introduction_letter_number ?: 'ثبت نشده' }}</div></div>@else<div class="mt-3 text-slate-500">اطلاعاتی ثبت نشده است.</div>@endif</details>
<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">مجوزها و شعب ({{ $dossier['branches']->count() }})</summary><div class="mt-3 rounded-lg bg-slate-50 p-3 text-sm">پروانه اصلی: {{ $company->activity_license_number ?: 'ثبت نشده' }} — اعتبار: {{ $company->activity_license_expires_on ? verta($company->activity_license_expires_on)->format('Y/m/d') : 'ثبت نشده' }}</div><div class="mt-3 grid gap-3 md:grid-cols-2">@foreach($dossier['branches'] as $branch)<div class="rounded-lg bg-slate-50 p-3 text-sm"><b>{{ $branch->name }} — {{ $branch->branch_type }}</b><div class="mt-1">{{ $branch->province }}، {{ $branch->city }} — مجوز {{ $branch->permit_number }}</div><div>اعتبار: {{ verta($branch->expires_on)->format('Y/m/d') }}</div></div>@endforeach</div></details>
<details class="rounded-xl border p-4"><summary class="cursor-pointer font-black">مدارک متفرقه ({{ $dossier['documents']->count() }})</summary><div class="mt-3 grid gap-3 md:grid-cols-2">@forelse($dossier['documents'] as $document)<div class="rounded-lg bg-slate-50 p-3 text-sm"><b>{{ $document->subject }}</b><p class="mt-1 text-slate-600">{{ $document->description }}</p><a class="mt-2 inline-block font-bold text-blue-700" href="{{ route('association.shahbaz.companies.documents.download',[$company,$document]) }}">دانلود {{ $document->original_name }}</a></div>@empty<div class="text-slate-500">مدرکی ثبت نشده است.</div>@endforelse</div></details>
</div></section>
@if($company->shahbaz_verification_status === 'pending_association_review')
<section class="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 class="text-lg font-black">بررسی اولیه پرونده</h2><form method="POST" action="{{ route('association.shahbaz.companies.initial-review',$company) }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf<label>نتیجه بررسی<select name="result" required class="mt-2 w-full rounded-lg border p-2"><option value="initial_approved">تأیید اولیه و آماده استعلام شحباز</option><option value="correction_required">برگشت برای رفع نقص</option><option value="rejected">رد درخواست</option></select></label><label class="md:col-span-2">توضیحات و دلیل<textarea name="description" required maxlength="3000" class="mt-2 w-full rounded-lg border p-2">{{ old('description') }}</textarea></label><div class="md:col-span-2"><button class="rounded-xl bg-blue-700 px-6 py-3 font-black text-white">ثبت نتیجه بررسی اولیه</button></div></form></section>
@endif
@if($company->shahbaz_verification_status === 'ready_for_shahbaz_check')
<form method="POST" action="{{ route('association.shahbaz.companies.review',$company) }}" class="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">@csrf
<label>نتیجه بررسی<select name="result" required class="mt-2 w-full rounded-lg border p-2"><option value="verified">تأیید شد</option><option value="correction_required">نیازمند اصلاح</option><option value="shahbaz_mismatch">دارای مغایرت</option><option value="company_not_found">شرکت یافت نشد</option><option value="follow_up">نیازمند پیگیری</option></select></label>
<label>شماره پروانه<input name="activity_license_number" class="mt-2 w-full rounded-lg border p-2"></label><label>تاریخ صدور (شمسی)<span class="relative mt-2 block"><input type="text" readonly autocomplete="off" name="activity_license_issued_on_jalali" class="jalali-picker w-full rounded-lg border py-2 pl-11 pr-3 text-center" dir="ltr" placeholder="انتخاب تاریخ صدور"><span class="pointer-events-none absolute left-3 top-2 text-lg">🗓️</span></span></label><label>پایان اعتبار (شمسی)<span class="relative mt-2 block"><input type="text" readonly autocomplete="off" name="activity_license_expires_on_jalali" class="jalali-picker w-full rounded-lg border py-2 pl-11 pr-3 text-center" dir="ltr" placeholder="انتخاب پایان اعتبار"><span class="pointer-events-none absolute left-3 top-2 text-lg">🗓️</span></span></label>
<label class="md:col-span-2">توضیحات کارشناس<textarea name="description" required class="mt-2 w-full rounded-lg border p-2"></textarea></label><div class="md:col-span-2"><button class="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white">ثبت نتیجه غیرقابل بازنویسی</button></div></form>
@endif
<h2 class="mt-8 font-black">تاریخچه</h2>@foreach($company->shahbazVerificationHistories->sortByDesc('id') as $row)<div class="mt-2 rounded-lg border p-3 text-sm">{{ verta($row->created_at)->format('Y/m/d H:i') }} — {{ $row->from_status }} ← {{ $row->to_status }} — {{ $row->description }}</div>@endforeach
<section class="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5">
<h2 class="text-lg font-black text-slate-900">تعیین هزینه و صدور صورتحساب</h2>
<p class="mt-1 text-sm text-slate-600">پس از تأیید مبلغ، صورتحساب برای شرکت قابل مشاهده خواهد بود و مبلغ قابل ویرایش نیست.</p>
@if($licenseRequests->isEmpty())
<div class="mt-4 rounded-xl bg-white p-4 text-sm text-amber-800">این شرکت هنوز درخواست پروانه‌ای ثبت نکرده است.</div>
@else
<form method="POST" action="{{ route('association.shahbaz.payments.store', $company) }}" class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">@csrf
<label>درخواست پروانه<select name="license_request_id" required class="mt-2 w-full rounded-lg border p-2"><option value="">انتخاب درخواست</option>@foreach($licenseRequests as $licenseRequest)<option value="{{ $licenseRequest->id }}" @selected(old('license_request_id') == $licenseRequest->id)>{{ $licenseRequest->tracking_code }} — {{ $licenseRequest->request_type }} — {{ $licenseRequest->status }}</option>@endforeach</select></label>
<label>مبلغ (ریال)<input type="number" name="amount" value="{{ old('amount') }}" min="10000" step="1" required class="mt-2 w-full rounded-lg border p-2" placeholder="مثلاً 70000000"></label>
<label class="md:col-span-2">شرح هزینه<textarea name="description" maxlength="2000" class="mt-2 w-full rounded-lg border p-2" placeholder="شرح هزینه صدور یا تمدید پروانه">{{ old('description') }}</textarea></label>
<div class="md:col-span-2"><button class="rounded-xl bg-amber-600 px-6 py-3 font-black text-white">تأیید مبلغ و صدور صورتحساب</button></div>
</form>
@endif
</section>
<section class="mt-6"><h2 class="font-black">سوابق صورتحساب‌ها</h2><div class="mt-3 space-y-2">@forelse($paymentRequests as $payment)<div class="rounded-xl border p-4 text-sm"><b>{{ number_format($payment->amount) }} ریال</b> — {{ $payment->status }} — درخواست {{ $payment->licenseRequest?->tracking_code }}<div class="mt-1 text-slate-500">{{ $payment->description ?: 'بدون توضیح' }} — {{ verta($payment->approved_at)->format('Y/m/d H:i') }} — {{ $payment->approver?->name ?? 'کاربر انجمن' }}</div></div>@empty<div class="rounded-xl border border-dashed p-4 text-sm text-slate-500">صورتحسابی ثبت نشده است.</div>@endforelse</div></section>
</div>@endsection
@section('scripts')
<script src="{{ asset('assets/js/persian-date.vendor.min.js') }}"></script><script src="{{ asset('assets/js/persian-datepicker.vendor.min.js') }}"></script>
<script>document.addEventListener('DOMContentLoaded',()=>{if(!window.jQuery||typeof jQuery.fn.pDatepicker!=='function')return;const placePicker=model=>requestAnimationFrame(()=>{const box=model.view.$container,inputRect=model.inputElement.getBoundingClientRect(),plot=box.find('.datepicker-plot-area')[0];if(!plot)return;const plotRect=plot.getBoundingClientRect(),above=window.innerHeight-inputRect.bottom<plotRect.height&&inputRect.top>plotRect.height,currentTop=parseFloat(box.css('top'))||0,delta=above?inputRect.top-4-plotRect.bottom:inputRect.bottom+4-plotRect.top;box.css('top',(currentTop+delta)+'px');});const pickerOptions={format:'YYYY/MM/DD',initialValue:false,initialValueType:'persian',autoClose:true,responsive:true,onlySelectOnDate:true,calendarType:'persian',calendar:{persian:{locale:'fa',showHint:false,leapYearMode:'algorithmic'},gregorian:{showHint:false}},navigator:{enabled:true,scroll:{enabled:true}},toolbox:{enabled:true,calendarSwitch:{enabled:false},todayButton:{enabled:true},submitButton:{enabled:false}},timePicker:{enabled:false},onShow:placePicker};jQuery('.jalali-picker').each(function(){jQuery(this).pDatepicker(pickerOptions);});const closeOnOutsideMove=e=>{if(e.target instanceof Element&&e.target.closest('.datepicker-container,.datepicker-plot-area'))return;jQuery('.jalali-picker').each(function(){const picker=jQuery(this).data('datepicker');if(picker)picker.hide();});};window.addEventListener('wheel',closeOnOutsideMove,{passive:true,capture:true});window.addEventListener('touchmove',closeOnOutsideMove,{passive:true,capture:true});});</script>
@endsection
