@extends('layouts.app')
@section('header_title','مدارک متفرقه')
@section('content')
<div dir="rtl" class="mx-auto max-w-6xl space-y-6">
<section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-2xl font-black">مدارک متفرقه</h1><p class="mt-2 text-sm text-slate-500">فایل‌های PDF یا تصویر، حداکثر ۲۰ مگابایت؛ مدارک بایگانی‌شده حذف نمی‌شوند.</p></div><a href="{{ route('company.shahbaz.dossier.show') }}" class="rounded-xl border px-5 py-3 font-black">بازگشت به پرونده</a></div></section>
@if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-2xl bg-rose-50 p-4 font-bold text-rose-800">{{ $errors->first() }}</div>@endif
@if($editable)<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-black">افزودن مدرک</h2><form method="POST" action="{{ route('company.shahbaz.misc-documents.store') }}" enctype="multipart/form-data" class="mt-4 grid gap-4 md:grid-cols-2">@csrf<label>موضوع<input name="subject" value="{{ old('subject') }}" required maxlength="200" class="mt-2 w-full rounded-xl border p-3"></label><label>فایل<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required class="mt-2 w-full rounded-xl border bg-white p-3"></label><label class="md:col-span-2">توضیحات<textarea name="description" maxlength="2000" class="mt-2 w-full rounded-xl border p-3">{{ old('description') }}</textarea></label><div class="md:col-span-2"><button class="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white">ثبت مدرک</button></div></form></section>@else<div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900">پرونده ارسال شده و تا اعلام نتیجه انجمن فقط قابل مشاهده است.</div>@endif
<section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($documents as $document)<article class="rounded-2xl border bg-white p-5 shadow-sm {{ $document->status === 'archived' ? 'opacity-60' : '' }}"><div class="flex items-start justify-between gap-3"><h2 class="font-black">{{ $document->subject }}</h2><span class="rounded-full px-3 py-1 text-xs font-bold {{ $document->status === 'active' ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-600' }}">{{ $document->status === 'active' ? 'فعال' : 'بایگانی' }}</span></div><p class="mt-3 text-sm text-slate-600">{{ $document->description ?: 'بدون توضیح' }}</p><div class="mt-4 text-xs text-slate-400">{{ $document->original_name }} — {{ number_format($document->file_size / 1024, 1) }} KB<br>{{ verta($document->created_at)->format('Y/m/d H:i') }}</div><div class="mt-4 flex gap-4"><a href="{{ route('company.shahbaz.misc-documents.download', $document) }}" class="font-bold text-emerald-700">دانلود</a>@if($editable && $document->status === 'active')<form method="POST" action="{{ route('company.shahbaz.misc-documents.archive', $document) }}">@csrf @method('DELETE')<button class="font-bold text-rose-700" onclick="return confirm('این مدرک بایگانی شود؟')">بایگانی</button></form>@endif</div></article>@empty<div class="md:col-span-2 xl:col-span-3 rounded-2xl border border-dashed bg-white p-8 text-center text-slate-500">مدرکی ثبت نشده است.</div>@endforelse</section>
</div>
@endsection
