<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('shahbaz_people', function(Blueprint $t){ $t->id(); $t->string('nationality')->default('ایرانی'); $t->string('national_code',30)->nullable()->unique(); $t->string('passport_number',50)->nullable()->unique(); $t->string('first_name'); $t->string('last_name'); $t->string('father_name')->nullable(); $t->string('birth_certificate_number',50)->nullable(); $t->date('birth_date')->nullable(); $t->string('birth_place')->nullable(); $t->date('issued_on')->nullable(); $t->string('issue_city')->nullable(); $t->string('gender',20)->nullable(); $t->boolean('is_veteran')->default(false); $t->timestamps(); });
  Schema::create('shahbaz_company_people', function(Blueprint $t){ $t->id(); $t->foreignId('company_id'); $t->foreignId('person_id'); $t->string('relation_type',30); $t->string('status')->default('draft'); $t->string('job_title')->nullable(); $t->string('board_position')->nullable(); $t->string('shareholder_type')->nullable(); $t->string('share_type')->nullable(); $t->decimal('share_amount',18,0)->nullable(); $t->decimal('share_percentage',8,4)->nullable(); $t->date('started_on')->nullable(); $t->date('ended_on')->nullable(); $t->text('note')->nullable(); $t->foreignId('created_by_user_id')->nullable(); $t->foreignId('archived_by_user_id')->nullable(); $t->dateTime('archived_at')->nullable(); $t->timestamps(); $t->foreign('company_id','shbz_cp_company_fk')->references('id')->on('companies')->cascadeOnDelete(); $t->foreign('person_id','shbz_cp_person_fk')->references('id')->on('shahbaz_people')->cascadeOnDelete(); $t->foreign('created_by_user_id','shbz_cp_created_by_fk')->references('id')->on('users')->nullOnDelete(); $t->foreign('archived_by_user_id','shbz_cp_archived_by_fk')->references('id')->on('users')->nullOnDelete(); $t->index(['company_id','relation_type','status'],'shbz_cp_company_type_status_idx'); });
 }
 public function down(): void { Schema::dropIfExists('shahbaz_company_people'); Schema::dropIfExists('shahbaz_people'); }
};
