<?php

return [
    'association' => [
        'shahbaz_company_review' => ['label' => 'کنترل و بررسی پرونده شرکت‌ها', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['association.shahbaz.*'], 'default' => false],
        'cmr_documents' => ['label' => 'کارتابل و چرخه اسناد e-CMR', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['admin.cmr.index', 'admin.cmr.show', 'admin.cmr.edit', 'admin.cmr.update', 'admin.cmr.destroy', 'admin.cmr.print', 'admin.cmr.tracking.*', 'admin.cmr.evidence', 'admin.cmr.amendments.*', 'admin.cmr.attachments.*', 'admin.cmr.handovers.*', 'admin.cmr.signatures.*', 'admin.cmr.finalize', 'admin.cmr.duplicate', 'admin.cmr.issue', 'admin.cmr.notifications.*', 'admin.cmr.cancel'], 'default' => false],
        'cmr_issuance' => ['label' => 'صدور e-CMR و راهنمای صدور', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['admin.cmr.create', 'admin.cmr.store', 'admin.cmr.help'], 'default' => false],
        'cmr_master_data' => ['label' => 'اطلاعات پایه CMR', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['admin.cmr.master-data.*'], 'default' => false],
        'cmr_company_settings' => ['label' => 'شماره‌ها، سیاست شرکت و قالب چاپ CMR', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['admin.cmr.company-settings.*'], 'default' => false],
        'cmr_financial' => ['label' => 'تعرفه و تنظیمات مالی CMR', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['admin.cmr.settings', 'admin.cmr.settings.*'], 'default' => false],
        'cmr_reports' => ['label' => 'گزارش‌های e-CMR', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['admin.cmr.reports.*'], 'default' => false],
        'dashboard' => ['label' => 'داشبورد انجمن', 'routes' => ['association.dashboard']],
        'requests' => ['label' => 'کارتابل درخواست‌های معلق', 'routes' => ['association.pending.*']],
        'issuance' => ['label' => 'صدور و تخصیص سریال', 'routes' => ['association.approved.*', 'association.permit.assign_serial']],
        'transit' => ['label' => 'مدیریت تردد', 'routes' => ['association.transit.*']],
        'archive' => ['label' => 'بایگانی پروانه‌ها', 'routes' => ['association.archive.*']],
        'reports' => ['label' => 'گزارش دوزوله‌ها', 'routes' => ['association.reports.*']],
        'financial' => ['label' => 'گزارش مالی صادرشده‌ها', 'routes' => ['association.issued-financial.*']],
        'crm' => ['label' => 'پیام‌ها و CRM انجمن', 'routes' => ['admin.association_crm.*']],
        'print_layouts' => ['label' => 'تنظیمات چاپ دوزوله', 'routes' => ['association.print-layouts.*']],
        'printing' => ['label' => 'چاپ پروانه', 'routes' => ['association.permit.print', 'association.permit.print_item']],
        'admin_dashboard' => ['label' => 'داشبورد کل ادمین', 'routes' => ['admin.dashboard'], 'default' => false],
        'companies' => ['label' => 'مدیریت شرکت‌ها', 'routes' => ['admin.companies.*'], 'default' => false],
        'countries' => ['label' => 'کشورها و مرزها', 'routes' => ['admin.countries.*'], 'default' => false],
        'inventory' => ['label' => 'انبار سریال دوزوله', 'routes' => ['admin.inventory.*', 'admin.admin.inventory.*'], 'default' => false],
        'allocations' => ['label' => 'تخصیص سهمیه‌ها', 'routes' => ['admin.allocations.*'], 'default' => false],
        'drivers' => ['label' => 'مدیریت جامع رانندگان', 'routes' => ['admin.drivers.*', 'admin.web.admin.driver.*'], 'default' => false],
        'tracking' => ['label' => 'ردیابی رانندگان روی نقشه', 'routes' => ['admin.tracking.*'], 'default' => false],
        'fleets' => ['label' => 'مدیریت جامع ناوگان', 'routes' => ['admin.fleets.*'], 'default' => false],
        'cargo_rules' => ['label' => 'قوانین مدارک دوزوله', 'routes' => ['admin.cargo_rules.*'], 'default' => false],
        'admin_financial' => ['label' => 'مدیریت مالی کل', 'routes' => ['admin.financial.*'], 'default' => false],
        'system_map' => ['label' => 'نقشه جامع سیستم', 'routes' => ['system.map'], 'default' => false],
        'driver_device_reset' => ['label' => 'ریست دستگاه اپلیکیشن رانندگان', 'routes' => ['driver-device-reset.*']],
        'account_security' => ['label' => 'تغییر رمز ورود پنل انجمن', 'routes' => ['association.account.security.*']],
        'driver_announcements' => ['label' => 'اطلاع‌رسانی به رانندگان', 'routes' => ['driver-announcements.*'], 'default' => false],
    ],
    'company' => [
        'shahbaz_overview' => ['label' => 'خانه پرونده و ارسال برای بررسی', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.dossier.*'], 'default' => false],
        'shahbaz_profile' => ['label' => 'مشخصات پایه شرکت', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.profile.*'], 'default' => false],
        'shahbaz_requests' => ['label' => 'درخواست‌های پروانه فعالیت', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.requests.*'], 'default' => false],
        'shahbaz_people' => ['label' => 'مدیران، اعضا و سهامداران', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.people.*'], 'default' => false],
        'shahbaz_fleet' => ['label' => 'پرونده ناوگان', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.fleet.*'], 'default' => false],
        'shahbaz_facilities' => ['label' => 'امکانات و محل فعالیت', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.facilities.*'], 'default' => false],
        'shahbaz_gazettes' => ['label' => 'روزنامه رسمی', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.gazettes.*'], 'default' => false],
        'shahbaz_registration' => ['label' => 'اطلاعات ثبتی شرکت', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.registration.*'], 'default' => false],
        'shahbaz_licenses' => ['label' => 'پروانه‌های فعالیت', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.licenses.*'], 'default' => false],
        'shahbaz_branches' => ['label' => 'مجوز شعب', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.branches.*'], 'default' => false],
        'shahbaz_manual_status' => ['label' => 'وضعیت استعلام دستی', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.manual-status.*'], 'default' => false],
        'shahbaz_misc_documents' => ['label' => 'سایر مدارک شرکت', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.misc-documents.*'], 'default' => false],
        'shahbaz_workflow' => ['label' => 'گردش کار پرونده', 'group' => 'shahbaz', 'group_label' => 'شهباز', 'routes' => ['company.shahbaz.workflow.*'], 'default' => false],
        'cmr_reports' => ['label' => 'گزارش‌های e-CMR شرکت', 'group' => 'cmr', 'group_label' => 'CMR', 'routes' => ['company.cmr-reports.*'], 'default' => false],
        'dashboard' => ['label' => 'داشبورد', 'routes' => ['dashboard']],
        'requests' => ['label' => 'ثبت و مدیریت درخواست', 'routes' => ['dozbalagh.*', 'web.dozbalagh.renew', 'company.dozbalagh.return_lash', 'company.dozbalagh.report_lost']],
        'issued' => ['label' => 'دوزوله‌های صادرشده', 'routes' => ['company.dozbalagh.issued', 'company.dozbalagh.copy']],
        'drivers' => ['label' => 'رانندگان', 'routes' => ['web.company.driver.*']],
        'tracking' => ['label' => 'ردیابی رانندگان روی نقشه', 'routes' => ['company.tracking.*']],
        'driver_messages' => ['label' => 'پیام رانندگان', 'routes' => ['company.driver_messages.*']],
        'association_crm' => ['label' => 'پیام‌ها و پشتیبانی انجمن', 'routes' => ['company.association_crm.*']],
        'fleets' => ['label' => 'ناوگان', 'routes' => ['web.company.fleet.*']],
        'reports' => ['label' => 'گزارش‌ها', 'routes' => ['report.*']],
        'wallet' => ['label' => 'کیف پول', 'routes' => ['company.wallet.*']],
        'profile' => ['label' => 'پروفایل و تغییر رمز', 'routes' => ['company.profile.*', 'company.password.*']],
        'driver_device_reset' => ['label' => 'ریست دستگاه اپلیکیشن رانندگان شرکت', 'routes' => ['driver-device-reset.*']],
        'driver_announcements' => ['label' => 'اطلاع‌رسانی به رانندگان شرکت', 'routes' => ['driver-announcements.*'], 'default' => false],
    ],
];
