<?php

return [
    'association' => [
        'dashboard' => ['label' => 'داشبورد انجمن', 'routes' => ['association.dashboard']],
        'requests' => ['label' => 'کارتابل درخواست‌های معلق', 'routes' => ['association.pending.*']],
        'issuance' => ['label' => 'صدور و تخصیص سریال', 'routes' => ['association.approved.*', 'association.permit.assign_serial']],
        'transit' => ['label' => 'مدیریت تردد', 'routes' => ['association.transit.*']],
        'archive' => ['label' => 'بایگانی پروانه‌ها', 'routes' => ['association.archive.*']],
        'reports' => ['label' => 'گزارش دوزوله‌ها', 'routes' => ['association.reports.*']],
        'financial' => ['label' => 'گزارش مالی صادرشده‌ها', 'routes' => ['association.issued-financial.*']],
        'crm' => ['label' => 'پیام‌ها و CRM انجمن', 'routes' => ['admin.association_crm.*']],
        'print_layouts' => ['label' => 'تنظیمات چاپ دوزوله', 'routes' => ['association.print-layouts.*']],
        'printing' => ['label' => 'چاپ پروانه', 'routes' => ['association.permit.print', 'association.permit.print_item']],
        'admin_dashboard' => ['label' => 'داشبورد کل ادمین', 'routes' => ['admin.dashboard'], 'default' => false],
        'companies' => ['label' => 'مدیریت شرکت‌ها', 'routes' => ['admin.companies.*'], 'default' => false],
        'countries' => ['label' => 'کشورها و مرزها', 'routes' => ['admin.countries.*'], 'default' => false],
        'inventory' => ['label' => 'انبار سریال دوزوله', 'routes' => ['admin.inventory.*', 'admin.admin.inventory.*'], 'default' => false],
        'allocations' => ['label' => 'تخصیص سهمیه‌ها', 'routes' => ['admin.allocations.*'], 'default' => false],
        'drivers' => ['label' => 'مدیریت جامع رانندگان', 'routes' => ['admin.drivers.*', 'admin.web.admin.driver.*'], 'default' => false],
        'tracking' => ['label' => 'ردیابی رانندگان روی نقشه', 'routes' => ['admin.tracking.*'], 'default' => false],
        'fleets' => ['label' => 'مدیریت جامع ناوگان', 'routes' => ['admin.fleets.*'], 'default' => false],
        'cargo_rules' => ['label' => 'قوانین مدارک دوزوله', 'routes' => ['admin.cargo_rules.*'], 'default' => false],
        'admin_financial' => ['label' => 'مدیریت مالی کل', 'routes' => ['admin.financial.*'], 'default' => false],
        'system_map' => ['label' => 'نقشه جامع سیستم', 'routes' => ['system.map'], 'default' => false],
        'driver_device_reset' => ['label' => 'ریست دستگاه اپلیکیشن رانندگان', 'routes' => ['driver-device-reset.*']],
        'account_security' => ['label' => 'تغییر رمز ورود پنل انجمن', 'routes' => ['association.account.security.*']],
        'driver_announcements' => ['label' => 'اطلاع‌رسانی به رانندگان', 'routes' => ['driver-announcements.*'], 'default' => false],
    ],
    'company' => [
        'dashboard' => ['label' => 'داشبورد', 'routes' => ['dashboard']],
        'requests' => ['label' => 'ثبت و مدیریت درخواست', 'routes' => ['dozbalagh.*', 'web.dozbalagh.renew', 'company.dozbalagh.return_lash', 'company.dozbalagh.report_lost']],
        'issued' => ['label' => 'دوزوله‌های صادرشده', 'routes' => ['company.dozbalagh.issued', 'company.dozbalagh.copy']],
        'drivers' => ['label' => 'رانندگان', 'routes' => ['web.company.driver.*']],
        'tracking' => ['label' => 'ردیابی رانندگان روی نقشه', 'routes' => ['company.tracking.*']],
        'driver_messages' => ['label' => 'پیام رانندگان', 'routes' => ['company.driver_messages.*']],
        'association_crm' => ['label' => 'پیام‌ها و پشتیبانی انجمن', 'routes' => ['company.association_crm.*']],
        'fleets' => ['label' => 'ناوگان', 'routes' => ['web.company.fleet.*']],
        'reports' => ['label' => 'گزارش‌ها', 'routes' => ['report.*']],
        'wallet' => ['label' => 'کیف پول', 'routes' => ['company.wallet.*']],
        'profile' => ['label' => 'پروفایل و تغییر رمز', 'routes' => ['company.profile.*', 'company.password.*']],
        'driver_device_reset' => ['label' => 'ریست دستگاه اپلیکیشن رانندگان شرکت', 'routes' => ['driver-device-reset.*']],
        'driver_announcements' => ['label' => 'اطلاع‌رسانی به رانندگان شرکت', 'routes' => ['driver-announcements.*'], 'default' => false],
    ],
];
