@extends('layouts.app')
@section('content')
<div class="space-y-5" dir="rtl">
 <div class="rounded-2xl bg-gradient-to-l from-[#064e3b] via-[#073b3a] to-[#071b2a] p-6 text-white shadow-lg"><h1 class="text-2xl font-black">گزارش‌های e-CMR</h1><p class="mt-1 text-sm text-emerald-100">گزارش اسناد حمل، هزینه‌ها، تحویل و مغایرت‌های شرکت</p></div>
 <form method="GET" class="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><input dir="ltr" name="from" value="{{ request('from') }}" class="rounded-xl border p-3" placeholder="از تاریخ شمسی 1405/01/01"><input dir="ltr" name="to" value="{{ request('to') }}" class="rounded-xl border p-3" placeholder="تا تاریخ شمسی 1405/12/29"><select name="status" class="rounded-xl border p-3"><option value="">همه وضعیت‌ها</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select><select name="driver_id" class="rounded-xl border p-3"><option value="">همه رانندگان</option>@foreach($drivers as $driver)<option value="{{ $driver->id }}" @selected((string)request('driver_id')===(string)$driver->id)>{{ $driver->first_name_fa }} {{ $driver->last_name_fa }}</option>@endforeach</select><select name="fleet_id" class="rounded-xl border p-3"><option value="">همه ناوگان</option>@foreach($fleets as $fleet)<option value="{{ $fleet->id }}" @selected((string)request('fleet_id')===(string)$fleet->id)>{{ $fleet->transit_plate }}</option>@endforeach</select><label class="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" name="exceptions_only" value="1" @checked(request()->boolean('exceptions_only'))> فقط مغایرت‌ها</label><button class="rounded-xl bg-emerald-700 p-3 font-black text-white">اعمال فیلتر</button><a href="{{ route('company.cmr-reports.export',request()->query()) }}" class="rounded-xl bg-slate-800 p-3 text-center font-black text-white">خروجی Excel/CSV</a><a href="{{ route('company.cmr-reports.index') }}" class="rounded-xl border p-3 text-center font-bold">پاک‌کردن فیلتر</a></form>
 <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">@foreach(['total'=>'کل اسناد','issued'=>'صادرشده','active'=>'در جریان','delivered'=>'تحویل‌شده','cancelled'=>'لغوشده','exceptions'=>'مغایرت','fees'=>'هزینه (ریال)'] as $key=>$label)<div class="rounded-2xl border bg-white p-4"><div class="text-xs text-slate-500">{{ $label }}</div><div class="mt-1 text-xl font-black {{ $key==='exceptions'&&$summary[$key]?'text-rose-600':'text-slate-900' }}">{{ number_format($summary[$key]) }}</div></div>@endforeach</div>
 <div class="overflow-x-auto rounded-2xl border bg-white"><table class="w-full min-w-[1000px] text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-right">شماره رسمی</th><th>وضعیت</th><th>راننده / ناوگان</th><th>مسیر</th><th>هزینه</th><th>تحویل</th><th>تاریخ صدور</th></tr></thead><tbody>@forelse($documents as $document)<tr class="border-t"><td class="p-3 font-mono font-bold" dir="ltr">{{ $document->company_serial ?: $document->number }}</td><td>{{ $statuses[$document->status] ?? $document->status }}</td><td>{{ $document->driver?->first_name_fa }} {{ $document->driver?->last_name_fa }}<div class="text-xs text-slate-400" dir="ltr">{{ $document->fleet?->transit_plate }}</div></td><td><span dir="ltr">{{ $document->taking_over_place }} → {{ $document->delivery_place }}</span></td><td>{{ number_format((float)$document->issuance_fee) }} ریال</td><td>@php($exception=$document->handovers->first(fn($h)=>in_array($h->outcome,['partial','damaged','refused'],true)))<span class="{{ $exception ? 'font-bold text-rose-600' : 'text-emerald-700' }}">{{ $exception?->outcome ?: ($document->handovers->last()?->outcome ?: '—') }}</span></td><td dir="ltr">{{ $document->issued_at ? verta($document->issued_at)->format('Y/m/d H:i') : '—' }}</td></tr>@empty<tr><td colspan="7" class="p-10 text-center text-slate-400">در این فیلتر سندی یافت نشد.</td></tr>@endforelse</tbody></table></div>{{ $documents->links() }}
</div>
@endsection
