@extends('layouts.admin')
@section('content')
@php
 $initialFields = $layout ? $layout->fields->map(fn($f) => $f->only(['field_key','x_mm','y_mm','width_mm','height_mm','font_size_pt','font_family','text_align','rotation_deg','is_bold','show_on_original','show_on_copy']))->values() : collect();
 $initialMasks = $layout ? $layout->masks->map(fn($m) => $m->only(['label','x_mm','y_mm','width_mm','height_mm','color']))->values() : collect();
@endphp
<div dir="rtl" class="p-5" x-data="layoutEditor()">
 <div class="mb-5 flex items-center justify-between"><div><h1 class="text-xl font-black">{{ $layout ? 'ویرایش قالب چاپ' : 'ساخت قالب چاپ' }}</h1><p class="mt-1 text-xs text-slate-500">فیلدها را روی برگه بکشید؛ مقادیر بر حسب میلی‌متر ذخیره می‌شوند.</p></div><a href="{{ route('association.print-layouts.index') }}" class="text-sm font-bold text-slate-500">بازگشت</a></div>
 @if($errors->any())<div class="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
 @if(session('success'))<div class="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{ session('success') }}</div>@endif
 <form method="POST" enctype="multipart/form-data" action="{{ $layout ? route('association.print-layouts.update',$layout) : route('association.print-layouts.store') }}" @submit="syncJson">
  @csrf @if($layout) @method('PUT') @endif
  <input type="hidden" name="fields_json" :value="JSON.stringify(fields)"><input type="hidden" name="masks_json" :value="JSON.stringify(masks)">
  <div class="grid gap-5 xl:grid-cols-[340px_1fr]">
   <aside class="space-y-4 rounded-2xl border bg-white p-4 shadow-sm">
    <div class="grid grid-cols-2 gap-3"><label class="col-span-2 text-xs font-bold">عنوان<input name="name" required value="{{ old('name',$layout->name ?? '') }}" class="mt-1 w-full rounded-lg border p-2"></label><label class="text-xs font-bold">کشور<select name="country_id" required class="mt-1 w-full rounded-lg border p-2">@foreach($countries as $country)<option value="{{ $country->id }}" @selected(old('country_id',$layout->country_id ?? null)==$country->id)>{{ $country->name }}</option>@endforeach</select></label><label class="text-xs font-bold">نوع مجوز<input name="permit_type" required value="{{ old('permit_type',$layout->permit_type ?? '') }}" class="mt-1 w-full rounded-lg border p-2"></label></div>
    <div class="grid grid-cols-2 gap-3"><label class="text-xs font-bold">عرض mm<input name="paper_width_mm" x-model.number="paperW" type="number" step=".1" class="mt-1 w-full rounded-lg border p-2"></label><label class="text-xs font-bold">ارتفاع mm<input name="paper_height_mm" x-model.number="paperH" type="number" step=".1" class="mt-1 w-full rounded-lg border p-2"></label><label class="text-xs font-bold">افست X<input name="offset_x_mm" value="{{ old('offset_x_mm',$layout->offset_x_mm ?? 0) }}" type="number" step=".1" class="mt-1 w-full rounded-lg border p-2"></label><label class="text-xs font-bold">افست Y<input name="offset_y_mm" value="{{ old('offset_y_mm',$layout->offset_y_mm ?? 0) }}" type="number" step=".1" class="mt-1 w-full rounded-lg border p-2"></label></div>
    <div class="grid grid-cols-2 gap-3"><label class="text-xs font-bold">جهت<select name="orientation" class="mt-1 w-full rounded-lg border p-2"><option value="portrait">عمودی</option><option value="landscape" @selected(($layout->orientation ?? '')==='landscape')>افقی</option></select></label><label class="text-xs font-bold">نسخه<input name="version" type="number" min="1" value="{{ old('version',$layout->version ?? 1) }}" class="mt-1 w-full rounded-lg border p-2"></label></div>
    <label class="block text-xs font-bold">تصویر مرجع<input name="background" type="file" accept="image/*" @change="previewFile" class="mt-1 block w-full text-xs"></label><label class="flex gap-2 text-xs font-bold"><input name="is_active" type="checkbox" value="1" @checked(old('is_active',$layout->is_active ?? true))> قالب فعال باشد</label>
    <div class="border-t pt-4"><label class="text-xs font-bold">افزودن فیلد<select x-model="newKey" class="mt-1 w-full rounded-lg border p-2"><option value="">انتخاب کنید</option>@foreach($catalog as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><button type="button" @click="addField" class="mt-2 w-full rounded-lg bg-sky-600 p-2 text-xs font-bold text-white">افزودن به برگه</button><button type="button" @click="addMask" class="mt-2 w-full rounded-lg bg-amber-500 p-2 text-xs font-bold text-white">افزودن پوشاننده شماره نمونه</button></div>
    <template x-if="selectedField"><div class="space-y-2 border-t pt-4 text-xs"><strong x-text="labels[selectedField.field_key]"></strong><div class="grid grid-cols-2 gap-2"><label>X<input x-model.number="selectedField.x_mm" type="number" step=".1" class="w-full rounded border p-1"></label><label>Y<input x-model.number="selectedField.y_mm" type="number" step=".1" class="w-full rounded border p-1"></label><label>عرض<input x-model.number="selectedField.width_mm" type="number" step=".1" class="w-full rounded border p-1"></label><label>ارتفاع<input x-model.number="selectedField.height_mm" type="number" step=".1" class="w-full rounded border p-1"></label><label>فونت<input x-model.number="selectedField.font_size_pt" type="number" step=".5" class="w-full rounded border p-1"></label><label>چرخش<input x-model.number="selectedField.rotation_deg" type="number" class="w-full rounded border p-1"></label></div><label class="flex gap-2"><input type="checkbox" x-model="selectedField.show_on_original"> چاپ روی اصل انجمن</label><label class="flex gap-2"><input type="checkbox" x-model="selectedField.show_on_copy"> نمایش نسخه شرکت/راننده</label><label class="flex gap-2"><input type="checkbox" x-model="selectedField.is_bold"> ضخیم</label><button type="button" @click="removeSelected" class="text-red-600">حذف فیلد</button></div></template>
    <button class="w-full rounded-xl bg-emerald-600 p-3 font-black text-white">ذخیره تنظیمات چاپ</button>
   </aside>
   <section class="overflow-auto rounded-2xl bg-slate-700 p-6"><div class="relative mx-auto bg-white shadow-2xl" :style="`width:${paperW*scale}px;height:${paperH*scale}px;background-size:100% 100%;background-image:${backgroundUrl?'url('+backgroundUrl+')':'none'}`" @mousemove="dragMove" @mouseup="drag=null" @mouseleave="drag=null">
    <template x-for="(mask,i) in masks" :key="'m'+i"><div class="absolute border-2 border-dashed border-amber-500 opacity-80" :style="boxStyle(mask)+';background:'+mask.color" @mousedown.prevent="startDrag($event,mask)"><span class="bg-amber-500 text-[9px] text-white">پوشاننده</span></div></template>
    <template x-for="(field,i) in fields" :key="'f'+i"><div class="absolute cursor-move border border-sky-500 bg-sky-100/70 text-center text-[10px] text-sky-900" :class="selectedField===field?'ring-2 ring-sky-600':''" :style="boxStyle(field)" @mousedown.prevent="selectedField=field;startDrag($event,field)" x-text="labels[field.field_key]"></div></template>
   </div></section>
  </div>
 </form>
</div>
<script>
function layoutEditor(){return {paperW:@json((float)($layout->paper_width_mm ?? 210)),paperH:@json((float)($layout->paper_height_mm ?? 297)),scale:2.5,fields:@json($initialFields),masks:@json($initialMasks),labels:@json($catalog),newKey:'',selectedField:null,drag:null,backgroundUrl:@json($layout?->background_path ? asset('storage/'.$layout->background_path) : null),addField(){if(!this.newKey)return;let f={field_key:this.newKey,x_mm:10,y_mm:10,width_mm:55,height_mm:8,font_size_pt:11,font_family:'Tahoma',text_align:'center',rotation_deg:0,is_bold:false,show_on_original:this.newKey!=='serial_number',show_on_copy:true};this.fields.push(f);this.selectedField=f},addMask(){this.masks.push({label:'پوشاندن شماره نمونه',x_mm:10,y_mm:10,width_mm:40,height_mm:8,color:'#ffffff'})},removeSelected(){this.fields=this.fields.filter(f=>f!==this.selectedField);this.selectedField=null},boxStyle(o){return `left:${o.x_mm*this.scale}px;top:${o.y_mm*this.scale}px;width:${o.width_mm*this.scale}px;height:${o.height_mm*this.scale}px;transform:rotate(${o.rotation_deg||0}deg)`},startDrag(e,o){this.drag={o,sx:e.clientX,sy:e.clientY,ox:+o.x_mm,oy:+o.y_mm}},dragMove(e){if(!this.drag)return;this.drag.o.x_mm=Math.max(0,+(this.drag.ox+(e.clientX-this.drag.sx)/this.scale).toFixed(1));this.drag.o.y_mm=Math.max(0,+(this.drag.oy+(e.clientY-this.drag.sy)/this.scale).toFixed(1))},previewFile(e){let f=e.target.files[0];if(f)this.backgroundUrl=URL.createObjectURL(f)},syncJson(){}}}
</script>
@endsection
